### ISSUE TITLE
Add a shape parameter to `WavySliderDefaults.Thumb()`

### ISSUE THREAD

**Issue by saket** [mahozad/wavy-slider#1]
It'd be really nice if the library allowed customizing the thumb's shape, mostly because Android's squiggly slider [no longer uses](https://9to5google.com/2022/10/05/android-13-qpr1-player/) a circle:

| Before | After |
| --- | --- |
| ![before](https://i1.wp.com/9to5google.com/wp-content/uploads/sites/4/2022/10/android-13-qpr1-beta-1-media-player-squiggle.jpeg?strip=info&w=500&ssl=1) | ![after](https://i1.wp.com/9to5google.com/wp-content/uploads/sites/4/2022/10/android-13-qpr1-beta-2-media-player-squiggle.jpeg?strip=info&w=500&ssl=1)

**Comment by mahozad** [comment]
@saket 
Hi. Thanks for your suggestion.

Please give me some time and I will try to add it.

**Comment by mahozad** [comment]
I was not aware that there is already an overloaded function in the Material 3 variant that accepts a custom thumb Composable.

Maybe, that suits your needs.

**Comment by saket** [comment]
True true, I can use that
