### ISSUE TITLE
Customizable animation duration

### ISSUE THREAD

**Issue by saket** [mahozad/wavy-slider#3]
I'd like to increase the animation duration, which is currently hardcoded to `1000ms`. Can `WaveSlider` take in an `animationSpec`?

**Comment by mahozad** [comment]
I think `animationSpec` is overkill. How about just adding another parameter called `animationDuration`? Or, replacing `animationDirection` parameter with a `velocity` parameter which specifies speed and direction?

**Comment by saket** [comment]
Yea just the duration sounds good because you'll never want to use any non-linear easing spec.

**Comment by mahozad** [comment]
It seems the current animation duration is `2000ms`.
`1000ms` is the animation duration of wave height when it is changed.
Did you mean the animation duration of wave height?

**Comment by saket** [comment]
Whoops I must have misread. The wave height animation duration of `1s` is fine IMO.
