### ISSUE TITLE
Optimize drawing of waves

### ISSUE THREAD

**Issue by saket** [mahozad/wavy-slider#4]
Creating a new `Path` object on every draw frame is not recommended as it may be expensive. Can it be cached somewhere? You can then use `Path#rewind()` on every frame to reset the points.

https://github.com/mahozad/wavy-slider/blob/bc5294b1bb55204bfafe88f9dc33acd5436dccd9/library/src/commonMain/kotlin/ir/mahozad/multiplatform/wavyslider/material3/WavySlider.kt#L522

**Comment by mahozad** [comment]
Hey again.

I created the path on the file top-level and then used path#reset or path#rewind as you suggested and executed `test#29` which has many sliders in it on a desktop PC and measured the fps of the app using Fraps.

https://github.com/mahozad/wavy-slider/blob/ac107ca5ade327181a1310796cb4f4d6424c69d3/library/src/desktopTest/kotlin/ir/mahozad/multiplatform/wavyslider/VisualTest.kt#L589-L620

The fps of the app on my system remained 20fps in all cases. So, no improvement.

Is this a good and reliable way to measure performance at all?
I've also marked most of the functions `inline` (do not know if it's a good idea).
Do you have any insight how I can optimize further?
Pull requests are welcome.

Sidenote: I tried the wavy slider in an app in another system with a less capable CPU and no Graphics card and Microsoft basic render driver (no graphics driver) and, unfortunately, the wave horizontal movement seemed to glitch a little occasionally.

**Comment by saket** [comment]
Hmm, do you see any performance changes if you test your code on a phone with not-so-stellar specs?

**Comment by mahozad** [comment]
unfortunately there is glitch every so often on the wave movement (probably because of garbage collection?)

**Comment by saket** [comment]
I'd say it's difficult to benchmark performance of a single optimization. I wouldn't be surprised if the performance is very comparable with or without this change on most devices. The hard part of optimizing performance is that the differences are often only noticeable when your composable is paired with other unoptimized/complex composables on a screen, and their allocations and expensive code add up beyond the 60fps threshold.

In general, minimizing allocations on hot paths is the right thing to do.

**Comment by mahozad** [comment]
Related: https://github.com/JetBrains/compose-multiplatform/issues/4199

**Comment by mahozad** [comment]
Found the source code of Android squiggly progress: https://android.googlesource.com/platform/frameworks/base/+/refs/heads/main/packages/SystemUI/src/com/android/systemui/media/controls/ui/SquigglyProgress.kt

It seems to rewind the path every time.

Funny that it also implements the wave using bezier curves.
