### ISSUE TITLE
Flatten slider when seeking

### ISSUE THREAD

**Issue by amirkazemzade** [mahozad/wavy-slider#8]
In android 13 when you are seeking the slider, the waves disappear to add more focus till you release the thumb and then the waves reappear. 
This can be done using dynamic wave height but then the hardcoded track height animation duration (which is 1000ms) makes it awkward.

I suggest two options:
1. Custom duration for height animation.
2. Adding flattenOnSeek option to the slider.

I think I can do the suggested options by my self. So if you are OK with it I will start working on it and then create a pull request for them.

**Comment by mahozad** [comment]
That'd be nice!

But, before adding any new features or changes, should figure out a way to resolve #7.

**Comment by amirkazemzade** [comment]
Sure!
For the first one, I suggest adding the `animationDuration` field with the default value of `1000ms` to the `Track` component. Then we should add this parameter to the main component as well and pass it down to the `Track`. 

For the second one we should somehow set the `animationDuration` parameter while dragging to something way shorter (I think it should be less than `200ms`, maybe `100ms`) for a faster transition. Also the `waveHeight` parameter should be set to 0.
I noticed `draggableState` variable in the `WavySliderImpl` component. I think we should use this variable to get the `isDragging` state of the slider. Then we could pass the `isDragging` to the `WavySliderImpl`'s track lambda as a parameter. This way both the implemented Track and custom Track from user implementation can use it.

**Comment by mahozad** [comment]
It's now even possible to have different animations for when the height is changed vs when the slider is interacted with.

See `Test #39` for an example:

https://github.com/mahozad/wavy-slider/blob/0fa041d73dfafe2d9e2115385b5d6106be6bcf26/library/src/desktopTest/kotlin/ir/mahozad/multiplatform/wavyslider/VisualTest.kt#L832-L887
